name: csven
version: '0.1.27'
summary: Order English words
description: CSVEN allows you to add an English word to mess it up and put it back together to learn how to write it through a game
base: core24
confinement: strict
grade: stable
license: GPL-3.0-or-later
compression: lzo

platforms: 
  amd64:
  arm64:
  armhf:

apps:
  csven:
    command: bin/csven
    desktop: share/applications/io.github.rsvzz.csven.desktop
    extensions: [gnome]
    common-id: io.github.rsvzz.csven
    slots: [csven-dbs]
    plugs: 
      - x11
      - wayland
      - desktop-legacy
      - desktop

parts:

  csven:
    plugin: meson
    source: https://github.com/rsvzz/csven-rs/releases/download/v0.1.27/csven_v0.1.27.tar.xz
    meson-parameters:
      - --prefix=/
      - --buildtype=release
      - --native-file=${SNAPCRAFT_PROJECT_DIR}/native.ini
    build-environment:
      - C_INCLUDE_PATH: ${SNAPCRAFT_STAGE}/include
      - LIBRARY_PATH: ${SNAPCRAFT_STAGE}/lib/x86_64-linux-gnu
    build-packages:
      - meson
      - rustc-1.85
      - cargo-1.85
    override-build: |
      cp -rv ${SNAPCRAFT_PROJECT_DIR}/vendor ${SNAPCRAFT_PART_BUILD}/vendor
      snapcraftctl build
      rm -r ${SNAPCRAFT_PART_INSTALL}/share/applications/io.github.rsvzz.csven.desktop
      cp -v ${SNAPCRAFT_PROJECT_DIR}/data/desktop/io.github.rsvzz.csven-snap.desktop ${SNAPCRAFT_PART_INSTALL}/share/applications/io.github.rsvzz.csven.desktop

slots:
  csven-dbs:
    interface: dbus
    bus: session
    name: io.github.rsvzz.csven